name: Update GTFS data cron job
on:
  workflow_dispatch:
jobs:
  update-cron:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Configure Git
      run: |
        git config --global user.name "GTFS Updater Bot"
        git config --global user.email "actions@github.com"
    - name: Update GTFS data
      run: ./fetch.py --commit --warn-http-errors
    - name: Push changes
      run: git push
